### ISSUE TITLE
Support for psc-ide

### ISSUE THREAD

**Issue by alternateved** [purcell/flymake-flycheck#1]
Hello, 

Would it be possible to use it with `psc-ide`? Currently, while using this package with setup similar to [this](https://github.com/purcell/emacs.d/blob/a3689baaec293f38a9545855ef8f61859bedcd14/lisp/init-flymake.el) and after starting `psc-ide`, no errors are being found unless `flymake-mode` gets manually reloaded. I realize that this could be out of scope, nevertheless I would really appreciate any help in that regard.

Best wishes,
alternateved

**Comment by purcell** [comment]
Ah yes, you're right that this doesn't work. I haven't debugged it fully yet to figure out why. It's a little while since I worked lots with Purescript. I'm guessing that I'd prefer using LSP now where possible.

**Comment by purcell** [comment]
I'm guessing that `(add-to-list 'flycheck-checkers 'psc-ide)` in your config file might help btw.

**Comment by alternateved** [comment]
> Ah yes, you're right that this doesn't work. I haven't debugged it fully yet to figure out why. It's a little while since I worked lots with Purescript. I'm guessing that I'd prefer using LSP now where possible.

Yes, I tried lsp-mode with Purescript for a while since [psc-ide-emacs](https://github.com/purescript-emacs/psc-ide-emacs) seems to be not actively maintained anymore (and packages like company or flycheck are hard-coded there), but some things like jump to definition doesn't work so well and having that functionality makes life a bit easier. For Purescript managed with spago, I do not experience those issues, but for the one managed with psc-package something is not quite right but I did not troubleshoot it enough.

> I'm guessing that `(add-to-list 'flycheck-checkers 'psc-ide)` in your config file might help btw.

Thank you! I'll definitively try that one out and see how it goes.

EDIT: Ah, it seems that `psc-ide` already is a part of `flycheck-checkers`, so that doesn't change much.

**Comment by purcell** [comment]
Hmm, I'll take a closer look if I get a little time. I personally use `eglot` rather than `lsp-mode`, but I haven't tried the purescript LSP yet.

**Comment by alternateved** [comment]
Personally I also prefer to use `eglot` when working on my projects - but lately I was in need for some of the features of `lsp-mode` like interactive project discovery that works out of the box.

It seems to me that Purescript LSP works pretty well on some of the projects that I tried it with - things like code actions, completions, code navigation works without a problem, so this issue/request is a rather niche thing. We use a forked version of Purescript and of Purescript LSP in my setting which seems to not play so well with `lsp-mode` or `eglot`. There are no problems with `psc-ide`, though. 

I would really appreciate your help here, but at the same time I feel like I am the only person with this problem so we may as well close this issue. I wanted to let you know about it, since in your configuration you also use `psc-ide`.
